### ISSUE TITLE
missing data after migration

### ISSUE THREAD

**Issue by joewilliams** [maxlapshin/mysql2postgres#32] opened 2011-09-14 18:12 UTC
Using this tool to migrate between mysql 5.1 and postgres 9.1 it seems to create all the tables properly but none of the data. In the command output I end up seeing something like:

Counting rows of invite_requests... 
Rows counted
Loading invite_requests...

 rows loaded in 0min 0s
Counting rows of org_invite_codes... 
Rows counted
Loading org_invite_codes...

Seems to suggest it didn't load any rows.

**Comment by paazmaya** [comment] 2016-08-21 09:03
Possibly related to #31

**Comment by paazmaya** [comment] 2016-08-21 09:09
Closing as duplicate of #31

**Closed by paazmaya** 2016-08-21 09:09 UTC
Labels: bug, needs example
